name: 'release'

on: push
     

jobs:
  img:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Create a Release'
        uses: elgohr/Github-Release-Action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          args: 222e
